# Generated by Django 2.2.6 on 2019-10-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coki_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                ('endereco', models.CharField(max_length=200, verbose_name='Foto')),
            ],
            options={
                'db_table': 'foto',
            },
        ),
    ]
